components_manager:
    task_processors:
        main-task-processor:
            worker_threads: $worker-threads

        fs-task-processor:
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:
        server:
            listener:
                port: $server-port
                task_processor: main-task-processor

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard

        handler-hello:
            path: /hello
            method: GET,POST,OPTIONS
            task_processor: main-task-processor

        handler-seller-stats:
            path: /seller_stats
            method: GET,OPTIONS
            task_processor: main-task-processor

        secdist: {}

        default-secdist-provider:
            environment-secrets-key: SECDIST_CONFIG

        clickhouse-database:
            secdist_alias: clickhouse-database
            initial_pool_size: 2
            max_pool_size: 5
            queue_timeout: 1s
            use_secure_connection: false
            compression: none

        kafka-consumer:
            group_id: stats-service
            topics:
              - order-events
            auto_offset_reset: earliest
            max_batch_size: 100
            poll_timeout: 500ms
            security_protocol: PLAINTEXT
            consumer-task-processor: main-task-processor
            consumer-blocking-task-processor: fs-task-processor
            task-processor: main-task-processor

        order-event-consumer: {}

        testsuite-support: {}

        dns-client:
            fs-task-processor: fs-task-processor


config_vars: /app/configs/config_vars.yaml
